"""empty message

Revision ID: 7ff371014f60
Revises: 4dba17d12aa9
Create Date: 2022-07-05 22:10:40.248865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff371014f60'
down_revision = '4dba17d12aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
